### ISSUE TITLE
GlobExpressions.GlobPatternException: Unable to parse SubSegment

### ISSUE THREAD

**Issue by Shane-XB-Qian** [artempyanykh/marksman#218]
Marksman encountered a fatal error

```log
GlobExpressions.GlobPatternException: Unable to parse SubSegment.    Expected one of CharacterWildcard | Wildcard | CharacterSetStart | CharacterSetEnd | Identifier. Found: LiteralSetSeperator
   at GlobExpressions.Parser.ParseCharacterSet()
   at GlobExpressions.Parser.ParseSubSegment()
   at GlobExpressions.Parser.ParseSegment()
   at GlobExpressions.Parser.ParseTree()
   at GlobExpressions.Glob.Compile()
   at GlobExpressions.Glob.IsMatch(String input)
   at Marksman.GitIgnore.GlobMatcherModule.checkGlob@50.Invoke(GlobPattern g) in /build/marksman/parts/marksman/build/Marksman/GitIgnore.fs:line 52
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 78
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at Microsoft.FSharp.Collections.SeqModule.TryFind[T](FSharpFunc`2 predicate, IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 668
   at Marksman.GitIgnore.GlobMatcherModule.ignores(GlobMatcher matcher, String path) in /build/marksman/parts/marksman/build/Marksman/GitIgnore.fs:line 54
   at Marksman.GitIgnore.GlobMatcherModule.ignoresAny@60.Invoke(GlobMatcher m) in /build/marksman/parts/marksman/build/Marksman/GitIgnore.fs:line 60
   at Microsoft.FSharp.Collections.SeqModule.Exists[T](FSharpFunc`2 predicate, IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 532
   at Marksman.Workspace.FolderModule.collect@341-4.GenerateNext(IEnumerable`1& next) in /build/marksman/parts/marksman/build/Marksman/Workspace.fs:line 344
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 405
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 441
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 77
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at Microsoft.FSharp.Collections.MapTreeModule.mkFromEnumerator[a,b](IComparer`1 comparer, MapTree`2 acc, IEnumerator`1 e) in D:\a\_work\1\s\src\fsharp\FSharp.Core\map.fs:line 443
   at Microsoft.FSharp.Collections.MapTreeModule.ofSeq[TKey,T](IComparer`1 comparer, IEnumerable`1 c) in D:\a\_work\1\s\src\fsharp\FSharp.Core\map.fs:line 455
   at Microsoft.FSharp.Collections.FSharpMap`2.Create(IEnumerable`1 ie) in D:\a\_work\1\s\src\fsharp\FSharp.Core\map.fs:line 590
   at Microsoft.FSharp.Collections.MapModule.OfSeq[TKey,T](IEnumerable`1 elements) in D:\a\_work\1\s\src\fsharp\FSharp.Core\map.fs:line 981
   at Marksman.Workspace.FolderModule.multiFile(String name, UriWith`1 root, IEnumerable`1 docs, FSharpOption`1 config) in /build/marksman/parts/marksman/build/Marksman/Workspace.fs:line 246
   at Marksman.Workspace.FolderModule.tryLoad(FSharpOption`1 userConfig, String name, UriWith`1 folderId) in /build/marksman/parts/marksman/build/Marksman/Workspace.fs:line 437
   at Marksman.Server.ServerUtil.readWorkspace(FSharpOption`1 userConfig, FSharpMap`2 roots) in /build/marksman/parts/marksman/build/Marksman/Server.fs:line 85
   at Marksman.Server.MarksmanServer.Initialize(InitializeParams par) in /build/marksman/parts/marksman/build/Marksman/Server.fs:line 528
```

**Comment by Shane-XB-Qian** [comment]
yea, i noticed one pattern had somehow abnormal (it's not my project, but just check one of someone's), 
it is `*.foo[o,p]`, i felt it should be no `,` in it.
but problem is it's not regarding to markdown, even it is parsing failed, why not just ignore it or warn a message (to client)?

**Comment by artempyanykh** [comment]
@Shane-XB-Qian thanks. Yeah, no question that it should be ignored. It's just sometimes dotnet libs are throwing exceptions where one doesn't expect. I asked for a pattern to add a regression test, that's it.
