### ISSUE TITLE
stderr error .../vim/lsp/rpc.lua:677  (neovim)

### ISSUE THREAD

**Issue by PMassicotte** [artempyanykh/marksman#236]
Hi, and thank you for the plugin. 

I have noticed that I am getting this error every time I am opening a markdown file:

LspLog: 

```bash
[START][2023-07-06 07:47:13] LSP logging initiated
[ERROR][2023-07-06 07:47:13] .../vim/lsp/rpc.lua:677	"rpc"	"/home/filoche/.local/share/nvim/mason/bin/marksman"	"stderr"	"[07:47:13 INF] <LSP Entry> Starting Marksman LSP server: {}\n"
```

LspInfo:

```bash
  Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: /home/filoche/.local/state/nvim/lsp.log
 Detected filetype:   markdown
 
 1 client(s) attached to this buffer: 
 
 Client: marksman (id: 1, bufnr: [4])
 	filetypes:       markdown
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             /home/filoche/.local/share/nvim/mason/bin/marksman server
 
 Configured servers list: lua_ls, pyright, r_language_server, jsonls, clangd, rust_analyzer, marksman

```
marksman version:

```bash
marksman --version
1.0.0-97da2ea
```

neovim version:

```bash
nvim --version 
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

Any ideas on what is going on?

**Comment by artempyanykh** [comment]
Thanks for reporting this @PMassicotte! This is just the way nvim treats logs from the server, not an error per-se. You can disable "info" level logs by running marksman with `marksman server -v=1`. LMK if it helps.

**Comment by PMassicotte** [comment]
Thank you very much for your answer. While I am there, do you have any recommendation for a good markdown linter/formatter?

**Comment by artempyanykh** [comment]
I think https://prettier.io/ is the standard.

**Comment by boiboiler** [comment]
I have same error...

marksman version:
```
1.0.0-2023-07-25
```

LspLog
```
Unhandled exception: System.AggregateException: One or more errors occurred. (Header does not end with expected
 character sequence: )
 ---> StreamJsonRpc.BadRpcHeaderException: Header does not end with expected
 character sequence:
   at StreamJsonRpc.HeaderDelimitedMessageHandler.ReadHeadersAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.HeaderDelimitedMessageHandler.ReadCoreAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.MessageHandlerBase.ReadAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.ReadAndHandleRequestsAsync()
   --- End of inner exception stack trace ---
   at Ionide.LanguageServerProtocol.Server.startWithSetup[client](FSharpFunc`2 setupRequestHandlings, Stream input, Stream output, FSharpFunc`2 clientCreator, FSharpFunc`2 customizeRpc) in /private/tmp/marksman-20230726-6060-f660to/marksman-2023-07-25/LanguageServerProtocol/LanguageServerProtocol.fs:line 179
   at Ionide.LanguageServerProtocol.Server.start@268-2.Invoke(FSharpFunc`2 customizeRpc)
   at Marksman.Program.startLSP(Int32 verbosity, Boolean waitForDebugger) in /private/tmp/marksman-20230726-6060-f660to/marksman-2023-07-25/Marksman/Program.fs:line 58
   at Marksman.Program.lspCommand@87.Invoke(Tuple`2 tupledArg)
   at FSharp.SystemCommandLine.CommandBuilders.SetHandlerInt@207-2.Invoke(InvocationContext ctx)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

neovim version:
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by artempyanykh** [comment]
Hi @boiboiler! That's a different error. Could you open a new issue for it and provide a bit more context on when/how the issue occurs?
